-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-01 18:55:42 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

--student id:30504457
--student name: Tan Wen Zheng

set echo on
SPOOL prop_rental_schema_output.txt

CREATE TABLE damage (
    dam_id     NUMBER(7) NOT NULL,
    rent_id    NUMBER(7) NOT NULL,
    dam_date   DATE NOT NULL,
    dam_time   DATE NOT NULL,
    dam_type   VARCHAR2(50) NOT NULL,
    dam_cost   NUMBER(6, 2) NOT NULL,
    pay_no     NUMBER(6, 2),
    prop_no    NUMBER NOT NULL
);

COMMENT ON COLUMN damage.dam_id IS
    'Surrogate key as identifier for damage datetime';

COMMENT ON COLUMN damage.rent_id IS
    'surrogate key as identifier for reat start date';

COMMENT ON COLUMN damage.dam_date IS
    'Damage date';

COMMENT ON COLUMN damage.dam_time IS
    'Damage time';

COMMENT ON COLUMN damage.dam_type IS
    'Damage type';

COMMENT ON COLUMN damage.dam_cost IS
    'Cost of damage';

COMMENT ON COLUMN damage.pay_no IS
    'payment identifier';

CREATE UNIQUE INDEX damage__idx ON
    damage (
        pay_no
    ASC );

ALTER TABLE damage ADD CONSTRAINT damage_pk PRIMARY KEY ( dam_id,
                                                          rent_id );

ALTER TABLE damage
    ADD CONSTRAINT nk_damage UNIQUE ( dam_date,
                                      dam_time,
                                      rent_id );

CREATE TABLE maintenance (
    maint_datetime   DATE NOT NULL,
    prop_no          NUMBER(7) NOT NULL,
    maint_desc       VARCHAR2(50) NOT NULL,
    maint_cost       NUMBER(6, 2) NOT NULL
);

COMMENT ON COLUMN maintenance.maint_datetime IS
    'Maintenance datetime';

COMMENT ON COLUMN maintenance.prop_no IS
    'property identifier';

COMMENT ON COLUMN maintenance.maint_desc IS
    'Maintenance description';

COMMENT ON COLUMN maintenance.maint_cost IS
    'Maintenance cost';

ALTER TABLE maintenance ADD CONSTRAINT maintenance_pk PRIMARY KEY ( maint_datetime
,
                                                                    prop_no );

CREATE TABLE owner (
    owner_no        NUMBER(7) NOT NULL,
    owner_title     CHAR(20) NOT NULL,
    owner_givname   CHAR(10) NOT NULL,
    owner_famname   CHAR(20) NOT NULL,
    owner_address   CHAR(50)
);

COMMENT ON COLUMN owner.owner_no IS
    'Owner identifier';

COMMENT ON COLUMN owner.owner_title IS
    'owner title';

COMMENT ON COLUMN owner.owner_givname IS
    'owner given name';

COMMENT ON COLUMN owner.owner_famname IS
    'owner family  name';

COMMENT ON COLUMN owner.owner_address IS
    'owner address';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_no );

CREATE TABLE payment (
    pay_no                 NUMBER(6, 2) NOT NULL,
    pay_date               DATE NOT NULL,
    pay_amount             NUMBER(6, 2) NOT NULL,
    pay_paidby             VARCHAR2(50) NOT NULL,
    pay_type               CHAR(6 CHAR),
    rent_lease_startdate   DATE NOT NULL,
    prop_no                NUMBER(7) NOT NULL,
    rent_id                NUMBER(7) NOT NULL
);

COMMENT ON COLUMN payment.pay_no IS
    'payment identifier';

COMMENT ON COLUMN payment.pay_date IS
    'payment date';

COMMENT ON COLUMN payment.pay_amount IS
    'payment amount';

COMMENT ON COLUMN payment.pay_paidby IS
    'payment by whom';

COMMENT ON COLUMN payment.pay_type IS
    'payment type';

COMMENT ON COLUMN payment.rent_lease_startdate IS
    'rent identifier';

COMMENT ON COLUMN payment.prop_no IS
    'property identifier';

COMMENT ON COLUMN payment.rent_id IS
    'surrogate key as identifier for reat start date';

ALTER TABLE payment ADD CONSTRAINT payment_pk PRIMARY KEY ( pay_no );

CREATE TABLE property (
    prop_no        NUMBER(7) NOT NULL,
    prop_address   CHAR(50) NOT NULL,
    prop_value     NUMBER(10) NOT NULL,
    owner_no       NUMBER(7) NOT NULL
);

COMMENT ON COLUMN property.prop_no IS
    'property identifier';

COMMENT ON COLUMN property.prop_address IS
    'property address';

COMMENT ON COLUMN property.prop_value IS
    'property value';

COMMENT ON COLUMN property.owner_no IS
    'Owner identifier';

ALTER TABLE property ADD CONSTRAINT property_pk PRIMARY KEY ( prop_no );

CREATE TABLE rent (
    prop_no                NUMBER(7) NOT NULL,
    rent_lease_startdate   DATE NOT NULL,
    rent_weekly_rate       NUMBER(6, 2) NOT NULL,
    rent_bond              NUMBER(10) NOT NULL,
    rent_lease_period      DATE NOT NULL,
    tenant_no              NUMBER(7) NOT NULL,
    rent_id                NUMBER(7) NOT NULL
);

COMMENT ON COLUMN rent.prop_no IS
    'property identifier';

COMMENT ON COLUMN rent.rent_lease_startdate IS
    'rent identifier';

COMMENT ON COLUMN rent.rent_weekly_rate IS
    'rental weekly rate';

COMMENT ON COLUMN rent.rent_bond IS
    'rent bond';

COMMENT ON COLUMN rent.rent_lease_period IS
    'rent lease period';

COMMENT ON COLUMN rent.tenant_no IS
    'tenant identifier';

COMMENT ON COLUMN rent.rent_id IS
    'surrogate key as identifier for reat start date';

ALTER TABLE rent ADD CONSTRAINT rent_pk PRIMARY KEY ( rent_id );

ALTER TABLE rent ADD CONSTRAINT nk_rent UNIQUE ( rent_lease_startdate,
                                                 prop_no );

CREATE TABLE teanant (
    tenant_no        NUMBER(7) NOT NULL,
    tenant_title     VARCHAR2(10) NOT NULL,
    tenant_famname   VARCHAR2(10) NOT NULL,
    tenant_givname   VARCHAR2(10) NOT NULL,
    tenant_phone     CHAR(8) NOT NULL,
    tenant_address   VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN teanant.tenant_no IS
    'tenant identifier';

COMMENT ON COLUMN teanant.tenant_title IS
    'tenant title';

COMMENT ON COLUMN teanant.tenant_famname IS
    'tenant family name';

COMMENT ON COLUMN teanant.tenant_givname IS
    'tenant given name';

COMMENT ON COLUMN teanant.tenant_phone IS
    'tenant phone number';

COMMENT ON COLUMN teanant.tenant_address IS
    'tenant address';

ALTER TABLE teanant ADD CONSTRAINT teanant_pk PRIMARY KEY ( tenant_no );

ALTER TABLE damage
    ADD CONSTRAINT damage_accountiblity FOREIGN KEY ( rent_id )
        REFERENCES rent ( rent_id );

ALTER TABLE damage
    ADD CONSTRAINT damage_payment FOREIGN KEY ( pay_no )
        REFERENCES payment ( pay_no );

ALTER TABLE property
    ADD CONSTRAINT owner_property FOREIGN KEY ( owner_no )
        REFERENCES owner ( owner_no );

ALTER TABLE maintenance
    ADD CONSTRAINT property_maintenance FOREIGN KEY ( prop_no )
        REFERENCES property ( prop_no );

ALTER TABLE rent
    ADD CONSTRAINT rent_property FOREIGN KEY ( prop_no )
        REFERENCES property ( prop_no );

ALTER TABLE payment
    ADD CONSTRAINT rental_payment FOREIGN KEY ( rent_id )
        REFERENCES rent ( rent_id );

ALTER TABLE rent
    ADD CONSTRAINT tenant_rental FOREIGN KEY ( tenant_no )
        REFERENCES teanant ( tenant_no );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             1
-- ALTER TABLE                             16
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
SPOOL off
set echo off